#!/usr/bin/python3

import sys
from powered_g import *
from giti_interactive import giti_interactive
from update import giti_update, giti_version, giti_update_necessity, is_git

script_path = os.path.dirname(os.path.realpath(__file__))


commands_dict = {
    "all": giti_all,
    "make": giti_makefile,
    "igit": giti_ignore,
    "del": giti_del,
    "header": giti_header
}


def main():
    giti_update_necessity()
    is_git()
    if len(sys.argv) < 2:
        print("GITI: Interactive GITI mode")
        giti_interactive()
        exit()
    command = sys.argv[1]
    args = sys.argv[2:]
    if command in commands_dict:
        commands_dict[command](args[0] if len(args) > 0 else "")
        exit()
    if command == "style":
        giti_coding_style(args)
        exit()
    if command == "--update":
        giti_update()
        exit()
    if command == "--version":
        giti_version()
        exit()
    else:
        title = ""
        comment = ""
        files = []
        if "-nc" in args:
            title = input("Title: ")
            files = args[args.index("-nc") + 1:]
        elif "-nt" in args:
            comment = input("Comment: ")
            files = args[args.index("-nt") + 1:]
        elif "-ntc" in args:
            files = args[args.index("-ntc") + 1:]
        elif "-nct" in args:
            files = args[args.index("-nct") + 1:]
        else:
            files = args
            title = input("Title: ")
            comment = input("Comment: ")
        generic_giti(command, title, comment, files)


main()
