#!/usr/bin/python3

import sys
from powered_g import *

commands_dict = {
    "all": giti_all,
    "makefile": giti_makefile,
    "coding_style": giti_coding_style,
    "ignore": giti_ignore,
    "delete": giti_del
}


def main():
    if len(sys.argv) < 2:
        print("GITI: No command given")
        exit()
    command = sys.argv[1]
    args = sys.argv[2:]
    if command in commands_dict:
        commands_dict[command](args[0] if len(args) > 0 else "")
    else:
        title = ""
        comment = ""
        files = []
        for arg in args:
            if arg == "-nc":
                title = args[args.index(arg) + 1]
                files = args[args.index(arg) + 2:]
                break
            elif arg == "-nt":
                comment = args[args.index(arg) + 1]
                files = args[args.index(arg) + 2:]
                break
            elif arg == "-ntc":
                files = args[args.index(arg) + 1:]
                break
        generic_giti(command, title, comment, files)


main()
